### ISSUE TITLE
Gobber mod for Fabric crashes Minecraft on start up.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [kwpugh/gobber_fabric#1]
Gobber crashes minecraft on startup. It's been happening to me through several versions. Love this on Forge so I hop[e to get Fabric working too.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/23/20, 8:36 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gobber2'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoClassDefFoundError: top/theillusivec4/curios/api/SlotTypeInfo$BuildScheme
	at com.kwpugh.gobber2.Gobber2.onInitialize(Gobber2.java:48)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: top.theillusivec4.curios.api.SlotTypeInfo$BuildScheme
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2918135928 bytes (2782 MB) / 4026531840 bytes (3840 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		allstackable: All Stackable 1.3.0
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		artifacts: Artifacts 2.0.2+1.16.4-fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		better_wandering_trader: Better Wandering Trader 1.6.2
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.8.3-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.4
		blue_endless_jankson: jankson 1.1.2
		blur: Blur (Fabric) 2.0.0
		bowinfinityfix: Bow Infinity Fix rv9
		campanion: Campanion 1.3.1+build.51
		canvas: Canvas Renderer 1.0.1257
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		chainmail: Chainmail 0.5.0
		charm: Charm 2.1.9
		charmonium: Charmonium 2.1.9
		cinderscapes: Cinderscapes 1.3.0+build.51
		cleancut: CleanCut mc1.16-2.1-fabric
		climbable: Climbable 0.2.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftablehorsearmour: Craftable Horse Armour & Saddle 1.16-1.3-Fabric
		crowdin-translate: CrowdinTranslate 1.2
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		durabilityviewer: Giselbaers Durability Viewer 1.16.4-fabric0.25.1-1.10
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		dynamo_api: Dynamo API 1.0.0+1.16.4
		effect: Effect Enchants 1.0.0
		eldritch_mobs: Eldritch Mobs 1.5.4
		engilib: EngiLib 1.0.0+1.16.4
		expandedstorage: ExpandedStorage 5.6.31
		fabric: Fabric API 0.28.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fairenchanting: FairEnchanting 1.2.0
		falling_tree: FallingTree 2.8.1
		fallingleaves: Falling Leaves 1.2
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.9.217
		fermion-orientation: Fermion Orientation 1.2.217
		fermion-varia: Fermion Varia 2.6.217
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		frex: FREX 4.2.183
		frex-events: FREX Events 1.1.11
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		gentlefawn: GentleFawn 1.1.2-MC1.16.3-fabric
		givemehats: Give Me Hats! 1.4
		glassential: Glassential 1.16.4-1.1.5
		gobber2: Gobber2 2.3.29
		illuminations: Illuminations 1.3.1
		jankson: Jankson 3.0.1+j1.2.0
		json-model-extensions: JSON Model Extensions 1.19.168
		kirin: Kirin UI 1.7-1.16.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		magna: Magna 1.4.2-1.16.2
		mechanicaltech: Mechanical Tech 0.2.0+1.16.4
		medievalweapons: Medieval Weapons 1.0.7
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.14.13+build.19
		more_gems: More Gems 1.1.13
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		mythicmetals: Mythic Metals 0.9.7
		netherite_nugget: Netherite Nugget 1.0.3
		netherite_plus: Netherite Plus Mod 1.1.0
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		parakeetmod: The Parakeet Mod 1.16.3-1.0.6
		patchouli: Patchouli 1.16.4-48-FABRIC
		phosphor: Phosphor 0.7.0+build.10
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.6-1.16.4
		presencefootsteps: Presence Footsteps r28+1.16.2
		pugh_lib: Pugh Lib 1.0.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		realistic_bakery_products: Realistic Bakery Products 1.1.7
		reborncore: Reborn Core 4.6.1+build.97
		repurposed_structures: Repurposed Structures 1.16.4-1.7.3
		resourceful_tools: Resourceful Tools 1.0.40
		ringsofascension: Rings of Ascension 1.1.1
		rocks: This Rocks! 1.2.2
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		satin: Satin 1.5.1
		simple_backpack: SimpleBackpack 1.0.33
		simplexterrain: Simplex Terrain 0.7.2
		special-circumstances: Special Circumstances 1.8.217
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stitchedsnow: Stiched Snow 1.0.0
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.7.1+build.162
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		tinytweaks: TinyTweaks 1.1.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-3
		traverse: Traverse 3.2.0+build.17
		trees-do-not-float: Trees Do Not Float 2.1.127
		trinkets: Trinkets 2.6.7
		upstream: Upstream 1.0.1
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		ward_blocks: Ward Blocks 1.0.19
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		worldedit: WorldEdit 7.2.1+299386a
		xaerominimap: Xaero's Minimap 20.29.1
		xaeroworldmap: Xaero's World Map 1.11.4
		xpstorage: XP Storage 1.3+1.16.4
		yungsapi: YUNG's API 1.16.4-Fabric-1
		zoob: Monster Of The Ocean Depths 2.5.0
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by kwpugh** [comment]
Looks like you do not have the required Curios API.
