### ISSUE TITLE
[1.16.5] Game Crash when building portal

### ISSUE THREAD

**Issue by THE-MecanOStarCrafter** [kwpugh/gobber_fabric#10]
My game crash as soon that  light the portal for going into a new dimension of the mod.
All the dimension of the mod are doing that for me.

**Comment by kwpugh** [comment]
Got a log or something to go on?   CCan't do much with that.

**Comment by Rubyz67** [comment]
happened to me 2 it doesnt make a crash report it just freezes my game

**Comment by Rubyz67** [comment]
and then when i relog the chunks never load

**Comment by Rubyz67** [comment]
MOD LIST:

[1.16.4]+MoreTooltips-1.0.1.jar
[Fabric] Wildfire Female Gender Mod-1.5.6.jar
adventurez-1.2.2.jar
aether-1.16.5-1.0.3.jar
amecs-1.3.4+mc.1.16.3.jar
Angel-Ring-Fabric-1.16.4-1.0.0.jar
architectury-1.12.145-fabric.jar
arstheurgia-1.0.6.jar
artifacts-3.2.0+fabric.jar
astromine-1.11.5+fabric-1.16.5.jar
autobackup-1.4.4.jar
Autofish-0.9.2-fabric-mc1.16.4.jar
backslot-1.1.9.jar
BasicNetherOres-1.16.5-5.5.0-Fabric.jar
battletowers-3.3.4-1.16.4.jar
bedspreads-fabric-1.3.1-1.16.4.jar
better-end-0.9.1-pre.jar
better-local-server-1.1.1.jar
better-nether-5.0.7.jar
BetterCaves-Fabric-1.16.5-1.1.jar
BetterMineshafts-Fabric-1.16.4-1.0.1.jar
betterthanmending-1.3.0.jar
bewitchment-1.16.5-8.jar
blame-1.16.4-2.4.1.jar
blockshifter-1.3.2+fabric-1.16.4.jar
blockus-2.1.1+1.16.5.jar
BOMD-1.0.1-1.16.5.jar
byg-1.1.7.jar
campanion-1.3.5.jar
Cardinal-Components-API-2.8.0.jar
carrier-1.7.5.jar
castle_dungeons-2.2-1.16.5-fabric.jar
cavebiomes-0.6.2.jar
cherishedworlds-fabric-1.3.0-1.16.4.jar
chestcavity-2.10.2.jar
cinderscapes-1.3.3.jar
cleancut-mc1.16-2.1-fabric.jar
cloth-config-4.11.19-fabric.jar
CompactStatusEffects-1.3.0.jar
conjuring-0.1.7.jar
cosmetic-armor-1.0.0.jar
crawl-0.8.2.jar
curios-fabric-0.0.13-1.16.5.jar
curiouselytra-fabric-1.1.1-1.16.5.jar
CursedMobWaifus-1.0.1.jar
DamageTilt-1.16-fabric-0.1.2.jar
dawn-1.8.jar
deep-dungeons-1.0.0-1.16.5.jar
desolation-1.1.1.jar
diggusmaximus-1.4.2-1.16.3.jar
DisableCustomWorldsAdvice-1.2.jar
DungeonsModLite-1.16.5-1.0.0.jar
dynamic-fps-2.0.1.jar
DynamicSoundFilters-1.2.0+1.16.5.jar
eldritch-mobs-1.6.9.jar
emotecraft-for-MC1.16.5-2.0.1-fabric.jar
equip-1.6.2.jar
expandedstorage-5.6.33+1.16.5.jar
fabric-api-0.33.0+1.16.jar
fabric-chunkpregen-0.3.3.jar
fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar
fabric-language-scala-1.0.0-fat.jar
fallingleaves-1.5.0+1.16.5.jar
fastfurnace-2.4.jar
fatxporbs-0.0.9+1.16.4.jar
ferritecore-2.0.4-fabric.jar
forglory-1.0.1+1.16.5.jar
gate-of-babylon-1.4.2-1.16.5.jar
geckolib-fabric-1.16.5-3.0.31.jar
gg_enchantments-1.1.1.jar
give-me-hats-1.16-1.5.1.jar
glassential-fabric-1.16.4-1.1.5.jar
golemancy-1.0.1.jar
GreaterEye-Fabric_1.16.5-1.1.5.jar
haema-1.6.0.jar
HealthOverlay-1.16.4-3.6.14.jar
Heartbond-1.16-1.0.0.jar
hellish-materials-0.12.2.jar
HWGMod-1.16.5-1.0.10.jar
identity-1.12.0-beta-1.16.5.jar
illuminations-1.4.9.jar
Impersonate-2.1.0.jar
indium-1.0.0_3-13-21.jar
indrev-1.9.4-BETA.jar
inmis-2.2.1-1.16.5.jar
inventory-control-tweaks-1.3.4+MC1.16.2-1.16.5.jar
InventorySorter-1.7.9-1.16.jar
lambdynamiclights-fabric-1.3.4+1.16.jar
lapisreserve-1.0.6.jar
libcd-3.0.3+1.16.3.jar
lightstones-1.3.0.jar
literally_chunk_loader
literally-chunk-loader-1.16-2.0.2.jar
lithium-fabric-mc1.16.5-0.6.4.jar
magic-lanterns-1.4.5.jar
mermod-fabric-1.3.jar
MiningDimensions_Fabric_1.16.5-1.0.4.jar
mixintrace-1.0.0.jar
mobz-2.4.6.jar
modmenu-1.16.9.jar
MoEnchantments-1.13.8.jar
MoreGems-Fabric_1.16.5-1.1.22.jar
mostructures-1.1.1+mc.1.16.5.jar
mousewheelie-1.6.4+mc1.16.4.jar
mythicmetals-0.9.9.jar
netherite-plus-mod-1.4.3-1.16.5-fabric.jar
noenchantcap-4.1.0.jar
notenoughbreeding-1.16.5-fabric.jar
notenoughcrashes-3.2.0-fabric.jar
OfflineSkins-1.16.5-v1-fabric.jar
okzoomer-4.0.1+1.16.2.jar
Origins-1.16.5-0.7.0.jar
Origins-Classes-1.16.5-1.1.1.jar
overworld-two-1.0.4.jar
passivecharms-1.0.0.jar
Patchouli-1.16.4-50-FABRIC.jar
Pehkui-2.0.0+21w14a.jar
PerspectiveModRedux-0.0.5.jar
phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
pling-1.3.0.jar
polymorph-fabric-0.0.10-1.16.5.jar
promenade-2.0.jar
quickshulker-1.1.14-1.16.jar
rare-ice-0.2.2.jar
repurposed_structures-1.16.5-1.10.4-fabric.jar
reroll-1.2.1-1.16.5.jar
respawnablepets-1.16.5-2.jar
RingsOfAscension-1.16.4-1.1.1.jar
RoughlyEnoughItems-5.11.218.jar
SakuraRosea-1.6.0-MC1.16.3-fabric.jar
sgod-1.0.0.jar
Silky-Spawners-2.1.0+build.2-1.16.jar
SimpleBackpack_Fabric_1.16.5-1.0.38.jar
simplesoundmuffler-1.16.2_0.2.1.jar
simpleteleporters-2.2.1.jar
slotlock-1.0.3-BETA.jar
smoothboot-fabric-1.16.5-1.6.0.jar
sodium-extra-0.2.2.jar
sodium-fabric-mc1.16.4-0.1.1-Next_Comp500_3-14-2021.jar
somnus-fabric-0.0.11-1.16.5.jar
spark-fabric.jar
spellbound-1.2.1.jar
staffofbuilding-1.2.6-1.16.5.jar
stoneholm-1.1.0.jar
SurvivalAdditions-1.3.2-Fabric-1.16.5.jar
TaxFreeLevels-1.1.jar
terrestria-2.2.0.jar
traverse-3.3.2.jar
trinkets-2.6.7.jar
TTLG-1.1.1.jar
vanguard-uninstaller.jar
vanilla-hammers-3.0.3-1.16.5.jar
vanillaenhanced-1.4.0.jar
WhiteRabbit-1.0.9+21w10a.jar
WildWorld-2.0.0+1.16.5.jar
wolves-with-armor-1.5.4-1.16.5.jar
worldedit-mod-7.2.5-dist.jar
wraith-alloy_forgery-1.0.8.jar
wraith-waystones-1.1.1.1.jar
wthit-2.7.0-fabric.jar
Xaeros_Minimap_21.7.0_Fabric_1.16.5.jar
XaerosWorldMap_1.13.3_Fabric_1.16.5.jar
YungsApi-1.16.5-Fabric-2.jar

**Comment by kwpugh** [comment]
without an error message or crash report, not much I can do.   It looks like you got quite a mix of mods covering 1.16.4, 1.16.5, and even snapshot 21w10a.  Only thing left to try is remove mods one by one and test until you find the one that is causing the conflict.

**Comment by Rubyz67** [comment]
ok i will find the confilct give me a day or 2

**Comment by Rubyz67** [comment]
its probably conflicting with one of gobber's or mining dimensions prerequisites

**Comment by kwpugh** [comment]
I didn't see Gobber in the list.  Are you using Gobber and Mining Dimensions together.  Don't use them together.

**Comment by Rubyz67** [comment]
both of them have the same glitch

**Comment by Rubyz67** [comment]
and i didnt use them together

**Comment by kwpugh** [comment]
makes sense, they are both setup the same way.

**Comment by Rubyz67** [comment]
i found the bug the newset version of the rather reborn fabric https://www.curseforge.com/minecraft/mc-mods/aether

**Comment by kwpugh** [comment]
Hmm, looks like they have a custom portal generator that may conflict with the one I'm using.

**Comment by THE-MecanOStarCrafter** [comment]
i've retry it but its seem fix in a newer version.

thanks for helping
