### ISSUE TITLE
[1.19.2] Fabric Ring of Attraction Bugged

### ISSUE THREAD

**Issue by MysticcX** [kwpugh/gobber_fabric#10]
The ring will work most of the time but will randomly not attract dropped items when the ring is active. It won't stop in the middle of it working but after being deactivated and then reactivated it sometimes will not work. In order to fix I have to put the ring inside of a chest deactivated and pick it up again.

**Comment by kwpugh** [comment]
Are you using Sodiu, Lithium, or another performance improvement mod?

**Comment by kwpugh** [comment]
Cannot re-produce and no further info provided, so closing.
