### ISSUE TITLE
1.18.2 fabric how to close auto feeding

### ISSUE THREAD

**Issue by downheart** [kwpugh/gobber_fabric#12]
I wonder know how to close the function of auto feeding of the armor in this mod
It is overpowered
I did not find any relative config

**Comment by kwpugh** [comment]
Each armor set has an option disable its auto feeding

example:  	"enableGobberHealthPerks": false

<img width="393" alt="Screen Shot 2022-10-25 at 5 34 16 AM" src="https://user-images.githubusercontent.com/8809210/197751602-cb38d9f5-8c1f-44b2-8a67-7832f928ed22.png">

**Comment by downheart** [comment]
thx

**Comment by downheart** [comment]
I found the gobber2config file, and it is a .class file, i turned it to .java by using jd-gui and i change the value. But i don't know how to exactly change the file in the mod file. I 've tring to google the answer but it didn't work, maybe you can give me some ideas?

**Comment by kwpugh** [comment]
that is not the config file.

it can be found in /config/gobber2/general.json5
edit  that file with a text editor

<img width="706" alt="Screen Shot 2022-10-26 at 6 05 02 AM" src="https://user-images.githubusercontent.com/8809210/198010558-054561eb-b055-4d5e-a805-d8823dcb4416.png">

**Comment by kwpugh** [comment]
here is a you tube vid on editing configs on windows:  https://www.youtube.com/watch?v=b8e9nc853Ak

**Comment by downheart** [comment]
OK i got it. Thank you very much. 
I don't know why I can't open it in the .minecraft folder but i can open it in other folder.
So i move the file to another folder then i can edit it
