### ISSUE TITLE
nether gobber sword 100% wither skull drop

### ISSUE THREAD

**Issue by THE-MecanOStarCrafter** [kwpugh/gobber_fabric#12]
Hi when i use the nether gobber sword on wither skeleton it as a 100% chance of drop. It would be great if it could be an option to adjust the percentage in the config file because as a server owner if i add this mod the economie could drop very fast. thanks

**Comment by kwpugh** [comment]
Sorry, that is the way it works.  I do not like putting config checks into Mixins, it causes unpredictable results.
