### ISSUE TITLE
[1.16.5] Portals teleport player to under and over the portal and die (stuck in wall or fall-damage)

### ISSUE THREAD

**Issue by DaisukeVN** [kwpugh/gobber_fabric#13]
The Portals of your Mods teleport players under and over the Portal. They always die through fall damage or stuck in wall (in Block under the Portal)

Can you please fix the portals? I using 1.16.5

**Comment by kwpugh** [comment]
Since you are the first/only person reporting this and the mod hasn't changed in 2 months, that tells me that you are likely having a unique mod conflict.

I would need a system log to even begin knowing how to know what might be happening.

**Comment by DaisukeVN** [comment]
Here is a log. I can't find information about the portals inside the log.
Ignore the "Chunksave errors". They are from another Mod...
[latest.log](https://github.com/kwpugh/gobber_fabric/files/6566889/latest.log)

**Comment by kwpugh** [comment]
It might be better nether, try without it and let me know.

**Comment by DaisukeVN** [comment]
But why Better Nether if I just want to teleport to Hunter & Mining Dimensions?

**Comment by kwpugh** [comment]
Maybe not.  Check for other mods in your pack that add portals.

Works fine on my end.

**Comment by kwpugh** [comment]
Seems to have disappeared with the updated embedded portal logic.
