### ISSUE TITLE
[1.16.5] Excavator breaking bedrock block

### ISSUE THREAD

**Issue by CrisInuyasha** [kwpugh/gobber_fabric#14]
The excavator when used with blocks that are adjacent with bedrock blocks is breaking the bedrock. When used directly on the bedrock it behaves normally not breaking it.

**Comment by kwpugh** [comment]
I tried all three excavators on dirt with adjacent bedrock and the bedrock does not break.  You may have another mod that is conflicting with my breaking code.

**Comment by CrisInuyasha** [comment]
I will try searching here what is the cause then
