### ISSUE TITLE
Ring Of Attraction [FABRIC]: Allow it to be used in the Trinkets slot

### ISSUE THREAD

**Issue by faahbio** [kwpugh/gobber_fabric#14]
I saw that one of the optional dependencies is Curious API, which allowed the user to have a "ring slot" but sadly it only worked until 1.16
Now on the 1.19.2 we have the Trinkets API (which I have downloaded) but it doesn't allow me to place the ring on the slot, I also downloaded NETS (not enough trinket slot) which uses the trinket api, but it also don't allow me to put the ring on any slot.

Would be cool to have this possibility, and the Trinkets API has a documentation to put your mod there, but sadly I don't know how to write code :(

**Comment by kwpugh** [comment]
Sorry, no plans for Trinkets.

it does however  work while placed in  player enderchest, which is great if you have a portable enderchest item.
