### ISSUE TITLE
[1.20] Ring of Air Walking kicks players with message "Flying is not enabled on this server"

### ISSUE THREAD

**Issue by NitroxydeX** [kwpugh/gobber_fabric#15]
**Describe the bug**
Using Ring of Air Walking kicks the player with the error message "flying is not enabled on this server"

As a workaround I've enabled flying in the server.properties

**Steps to reproduce the behavior:**

Use Ring of Air Walking while allow-flight is set to false

There has to be some sort of event to make it possible without setting the server.properties rule. I know that Forge has this kind of event, not sure about Fabric.

**Comment by kwpugh** [comment]
Were you using the Air Walking with standard walking speed or some sort of Speed potion or item?

I will take a look at this in the future, but it won't be until May/June of next year.

You will want allow-flight on away with gobber since there are other items that will need it anyway.

**Comment by purejosh** [comment]
As an experienced server owner, this is not something the developer can fix. Please enable allow-flight in your server config. 

(NOTE: This does not give the ability for users to fly on their own! It simply stops them from being kicked, if flight is detected, and many mods including simple ones like double jump will trigger this behavior.)

**Comment by kwpugh** [comment]
No further work here.
