### ISSUE TITLE
[1.16.5] the original nether portal can not use any more

### ISSUE THREAD

**Issue by DEADsamzxc9850** [kwpugh/gobber_fabric#15]
after using the mod, the original nether portal are not allow to in. it will just stay the animation and nothings happen

**Comment by kwpugh** [comment]
I would. need a system log to understand what is going on for you.   I tested and it works fine for me and others.  Sounds like you have another mod that is conflicting.

**Comment by kwpugh** [comment]
Could not replicate and received no additional data to be able to debug.
