### ISSUE TITLE
Staff of the Farmer grow Glow Lichen too far

### ISSUE THREAD

**Issue by NoElcDfb** [kwpugh/gobber_fabric#16]
Game Version: 1.19.2
Mod Version: Fabric-1.19.2-2.6.61
Hello, I found when using **_Staff of the Farmer_**, the **_Glow Lichen_** will grow and spread very fast and extend faraway which out of 12 blocks and won't stop.
I don't sure is it design for it, so I give this Issue for you. Thank you

**Comment by Grady-js** [comment]
Also happening to me on version 1.19.3, with the Ring and Staff versions of the item.

**Comment by rockbyo5** [comment]
I think what @NoElcDfb meant is "Farmer items have no cooldown applied regardless of setting, have a range somewhere between 60 and 300 regardless of setting and this issue applies to: tree saplings, crops and any other **bleep** thing you can farm"

**Comment by mohamad4444** [comment]
Same, it is impossible to remove now them now. Staff of farmer needs adjustment especially for glow lichen

**Comment by ponduzn** [comment]
![image](https://github.com/kwpugh/gobber_fabric/assets/11321675/973bedc1-f57e-43e2-b15f-36be554f4b12)
Seems to happen in a 8x8 chunk size, takes over completely within those chunks, also inside caves, in a matter of seconds, even with cfg settings for horizontal and vertical distance lowered drastically.

**Comment by theebs** [comment]
Would it be possible to add a blacklist to the options for the staff and ring?

**Comment by coloso730** [comment]
Hello, have you been able to fix the problem with the glow lichen?

**Comment by kwpugh** [comment]
fixed in latest releases
