### ISSUE TITLE
Rings attachable in rings trinket slot

### ISSUE THREAD

**Issue by kalixdrake** [kwpugh/gobber_fabric#17]
Is it possible for ring like the ring of strenght for example, or the ring of experience, to get attachable to rings trinkets and keep their functionality? 

Currently they are not even attachable, i think because of the "works while in off-hand" condition, but it would be fantastic if you add the option that if there are trinkets for them, they would be attachable.

Thank you.

**Comment by vizthex123** [comment]
I use the standalone Ender and Attraction ring mods on 1.19.3, would love if all of them had Trinkets support.

Though it's apparently the "glove" slot (or at least, that's what [angel ring](https://www.curseforge.com/minecraft/mc-mods/azuredooms-angel-ring) uses)

**Comment by kwpugh** [comment]
No trinket support planned.

**Comment by vizthex123** [comment]
bruh, why?
