### ISSUE TITLE
Accessories in 1.17 

### ISSUE THREAD

**Issue by DNewman5** [kwpugh/gobber_fabric#18]
The Curios API has been discontinued for fabric 1.17+. The Trinkets API is the only accessory API for 1.17 on fabric.

The game will load with Gobber installed, but of course none of the rings will go in the ring slots provided by Trinkets.

**Comment by kwpugh** [comment]
This is an ongoing project, no issue needed.

**Comment by milkev** [comment]
is this still ongoing? the ring of attraction doesnt have any trinkets support (in fact, curseforge lists curios as its dependency for the 1.17 version...)

**Comment by kwpugh** [comment]
I have not decided whether or not I'm going to add Trinkets support to my mods.

**Comment by milkev** [comment]
if you would like votes, i vote for trinkets support
