### ISSUE TITLE
[1.17] OreGen Diff with CavesAndCliffsPreview

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [kwpugh/gobber_fabric#19]
1.17(part 1 , june 2021 )
Gobber2-Fabric-1.17-2.4.10.jar

gobber is generated when CavesAndCliffsPreview.zip is not used in WORLD GENERATION
effects new worlds and existing snapshot worlds

everting works fine on new orlds generated without
CavesAndCliffsPreview.zip ( april 2021) datapack 

Gobber2-Fabric_21w11a-2.4.8.jar is NOT working with actual 1.17
but was working on 21w11a 

regards

**Comment by kwpugh** [comment]
21w19 broke compatibility with the jump to java 16.  Snapshots are done and should not be used.   I do not work on compatibility with data packs, too many out there.

**Comment by kwpugh** [comment]
Ore gen works fine, don’t use out dated data packs.

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
why the datapack 
from minecraft.net ( official site)

Features intended for release in the second Caves & Cliffs update for this year (1.18) can still be accessed via the Caves & Cliffs Prototype Data Pack.  

What is the Caves & Cliffs Prototype Data Pack? 

This data pack allows you to use features that are under development and intended to be released in the second Caves & Cliffs update in your Minecraft: Java Edition worlds.  

How do I access the Caves & Cliffs Prototype Data Pack?  

Important: Using the Caves & Cliffs Prototype Data Pack to access features still under development means that your world might crash, break, or not work with future updates. 

When creating a new world:  

    Download the data pack 

Even with the updated one CavesAndCliffsPreview.zip (103Kb) the oregen doesn't work, 
without no problem.
__________________________________________________________________

It's of course your decision, not supporting the upcoming 1.18 features, as well as gobber2

therefore the mod is useless ( in survival) for those, who want play the new ( 1.18) version,
having the new world dimensions


other mods, for example "Adabranium"
curseforge.com_minecraft_mc-mods_adabranium
use a different way for oregen, so it works,
adamantin and vibranium are generated -64 to +64 

best regards, daniel

by the way, 
i dont want to critisize you, you are a million more better programmer than i ever will be,
i just wanted to point out that issue.

**Comment by kwpugh** [comment]
[Gobber2-Fabric-1.17-2.4.11.jar.zip](https://github.com/kwpugh/gobber_fabric/files/6644426/Gobber2-Fabric-1.17-2.4.11.jar.zip)

Try this version.   NOTE: there is an option in the ores config to enable CavesAndCliffsPreview Oregen.

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
ok
tests so far
"cacpEnable": true,

Gobber ore is generated in Overworld and Nether in NEW generated testworld
Gobber ore is generated in Overworld and Nether in in EXISTING 1.17 world (new chunks)
          ( changing  CavesAndCliffsPreview to newest version)

the ore's are generated is very rare, in my opinion much rarer than in 21w11a 
the relation seems to me 1:1  luckyblock:gobber Ore
regards, daniel

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
Something weird

these mods only are installed

14.06.2021  04:55                 0 all.txt
02.06.2021  02:02           989.231 cloth-config-5.0.34-fabric.jar
13.06.2021  04:25           943.189 fabric-api-0.35.1+1.17.jar
14.06.2021  04:10         1.432.245 Gobber2-Fabric-1.17-2.4.11.jar
21.11.2020  20:17            11.668 RingOfMiner-Fabric_1.17-1.1.0.jar   my miner 
09.06.2021  05:33         1.162.097 RingsOfAscension-1.17-1.0.jar     for night vidion
09.06.2021  05:33           199.404 trinkets-3.0.0.jar


config
	*/
	"cacpEnable": true,
	/* 
	   
	   ***********************
	   Gobber Ore
	   ***********************
	*/
	"gobberEnable": true,
	"gobberVeinSize": 4,
	"gobberMaxLevel": 30,
	"gobberPerChunk": 20,
	/* 


created a new world (without datapack)

strip mined down
NONE of the Vanilla ores are generated

created a new world (WITH datapack)

strip mined down

Vanilla ores are ok , gobber extreeeemly rare

new config

*/
	"cacpEnable":false,
	/* 
	   
	   ***********************
	   Gobber Ore
	   ***********************
	*/
	"gobberEnable": true,
	"gobberVeinSize": 10,
	"gobberMaxLevel": 10,
	"gobberPerChunk": 20,
	/* 

new world , no datapack 

everythin works like intended 
vanilla ores ok
gobber massive at max 10

new world, with datapack

no gobber

________________________

my personal conclusion:

DONT'T USE WITH CavesAndCliffsPreview.zip

if i would you

declare the mod not compatible with  CavesAndCliffsPreview.zip
wait for 1.18 or whatever they will call it,
and then,
test the oregen.

best regards,
greeting from early morning bavaria
daniel

**Comment by kwpugh** [comment]
Done and done.
