### ISSUE TITLE
[1.16.4] Vanilla Unbreaking Enchant Breaks End Armour Unbreakable Tag

### ISSUE THREAD

**Issue by SavageKiller13** [kwpugh/gobber_fabric#2]
Whenever the End Armour is enchanted with Unbreaking the Armour loses its Unbreakable tag and takes damage.

The way to reproduce this is to put the armour into the enchanting table and whenever unbreaking is applied the armour loses the unbreakable tag.

**Comment by kwpugh** [comment]
![Screen Shot 2020-12-27 at 8 33 32 PM](https://user-images.githubusercontent.com/8809210/103185635-d3b90b00-4882-11eb-99e8-4e0f9e968166.png)

There must be something else going on.   I tried enchanting a piece of end armor in a table with unbreaking and it retains the unbreakable tag and remains "unbreakable".    Did you craft the end armor or pull it out of creative tab?   The unbreakable tag is added when the item is crafted, some end items taken from creative do not have the tag.

**Comment by kwpugh** [comment]
I testing this out on the Dank server and works fine there to.

**Comment by kwpugh** [comment]
Working as designed
