### ISSUE TITLE
[1.18.2] Ring of Return drains all experience for interdimensional travel.

### ISSUE THREAD

**Issue by JedRedd** [kwpugh/gobber_fabric#2]
I tested whether the Ring of Return from Version 2.5.74 for 1.18.2 would work through different dimensions. entered the nether and used it to return to the Overworld, it worked and drained all my experience levels (591 levels). Attempted to duplicate this and set my experience to 30 levels, entered the nether then used the ring to teleport back and it drained all 30 levels.

I am aware that some mods will use up experience for teleportation between dimensions but I haven't seen a mod that used up this much experience for one teleport, is it supposed to do this?

Also while I do have other mods installed none are for modifying the nether, modifying travel between dimensions, or for teleporting except for Xaero's Minimap which has a teleport function ~~but does not use up experience.~~, upon further tests Xaero's Minimap (XsM) teleporting does drain all experience, I am unsure if it is either Gobber or XsM or having both that causes the problem.

**Comment by kwpugh** [comment]
Fixed in dev, will be in future updates.

**Comment by kwpugh** [comment]
Refactored to use the FabricDimensions.teleport() instead of direct mojang code.
