### ISSUE TITLE
[1.16.5] Gobber crashes when certain mods are enabled

### ISSUE THREAD

**Issue by JLewis1309** [kwpugh/gobber_fabric#2]
For whatever reason it seems like if i enable these mods with gobber(fabric) minecraft wont start:
Caelus API
ClickThrough
Colyra
Cosmetic Armor

Enabling ANY of those mods seems to cause the issue
Crash Log: https://pastebin.com/S0zHdUZL
ModList: https://i.imgur.com/vRFWmMO.png

**Comment by kwpugh** [comment]
IS the crash client, server, or both?

**Comment by kwpugh** [comment]
Ok, so I loaded up with the latest of those mods and Gobber.   I don't get a crash on the client.  I did notice that including Colytra disables the gliding feature of the End Armor in Gobber.  I will try on my server to see if I get a crash.

**Comment by kwpugh** [comment]
I tested out the combo on my server, no crash.  I am using the latest version of ClickThrough.  You may want to try updating to that.

**Comment by kwpugh** [comment]
Are you using Fabric 1.16.5?

**Comment by JLewis1309** [comment]
Fabric 1.16.4
am using the latest 1.16.4 version of ClickThrough as well. But its crashing for me when i enable ANY of those mods not just all of them..so if i enable Cosmetic Armor and the others are disabled it doesnt work and the same for the rest of them

**Comment by JLewis1309** [comment]
Added a few other unrelated mods and those also are causing it to crash with similar looking crash logs so seems with Gobber has something weird going on making it not wanna work with other mods or just something else is going on with my modlist.
But Disabling Gobber seems to let all the mods work just fine so its weird

**Comment by JLewis1309** [comment]
I think the bug might have something to do with having too many mods. I did a test
Enable Mod A- Crash
Disable Mod A- Loads
Disable Random Mod B & Enable Mod A - Loads

**Comment by kwpugh** [comment]
Did you try bumping up the memory settings in the launcher?

**Comment by JLewis1309** [comment]
Just Tried, didnt seem to help any

**Comment by kwpugh** [comment]
how many mods?   How much RAM are you setting?

**Comment by JLewis1309** [comment]
50-60 mods and ram was set to 1024mb min and 2048 max but upped max by 1k and still crashed like normal

**Comment by kwpugh** [comment]
how much RAM does your computer have?

**Comment by JLewis1309** [comment]
8gb

**Comment by kwpugh** [comment]
try 3072mb

**Comment by JLewis1309** [comment]
still fails to launch

**Comment by kwpugh** [comment]
what about 4096mb

**Comment by kwpugh** [comment]
Windows 10?

**Comment by JLewis1309** [comment]
4096mb ram and still fails to launch and yup windows 10

**Comment by kwpugh** [comment]
Can you post your launcher log?

**Comment by JLewis1309** [comment]
https://pastebin.com/Kpp7tjTD

**Comment by kwpugh** [comment]
yeah, it looks like your setup doesn't like one of my mixing in Gobber.

**Comment by JLewis1309** [comment]
I Just finished my playthru of these mods i was playing with so it doesnt matter for me personally just more hoping it can help prevent future bugs :P

**Comment by kwpugh** [comment]
update things to 1.16.5 and see if you still have the problem.

**Comment by JLewis1309** [comment]
changed MC version to 1.16.5
Go latest 1.16.5 Gobber Version and had to get snad 1.16.5 version
Failed to Launch with what looks like the same error...i didn't check every mod to make sure i had the right 1.16.5 version just because..yeah..im lazy lol

**Comment by kwpugh** [comment]
update ClickThrough to 1.16.5

**Comment by JLewis1309** [comment]
same "Mixin apply Failed gobber2...." error :/

**Comment by kwpugh** [comment]
one of the mods you have is stepping on my mixin,   You would have to remove mods one at a time and check which one it is.

**Comment by kwpugh** [comment]
which launcher are you using?

**Comment by JLewis1309** [comment]
thats the thing tho, theres multiple different mods that id have to remove for it to work, its not just 1 mod.
MultiMC launcher

**Comment by kwpugh** [comment]
yeah, it could be the interaction of more than one mod.

**Comment by JLewis1309** [comment]
like right now i have 50 mods enabled, and 9 disabled, i enable any one of those 9 and it fails to launch

**Comment by kwpugh** [comment]
did you eliminate 1 mod at a time?  How do you know it was multiple mods?

**Comment by kwpugh** [comment]
what are the 9?

**Comment by JLewis1309** [comment]
50 enabled - Loads
Enable autofish mod - fails
disable autofish and enable Backslot - fails
Keep Backslot enabled and disable Inventory HUD and Inventory Sorter - Loads

I dont think the specific mods matter its just something weird happening where if i disable 1-2 mods to enable another it works, even if that mod before would cause it to crash

**Comment by kwpugh** [comment]
I'm looking for what they might have in common.

**Comment by JLewis1309** [comment]
Backslot enabled - fail
disable Inventory Hud - Fail
Disable Inventory Hud AND Infinite Fix - Loads

**Comment by kwpugh** [comment]
when you updated MC to 1.16.5, did you also update Fabricc API as well?

**Comment by JLewis1309** [comment]
just updated Fabric API but doesnt seem to have changed anything

**Comment by kwpugh** [comment]
<img width="570" alt="Screen Shot 2021-02-13 at 7 35 36 AM" src="https://user-images.githubusercontent.com/8809210/107851244-1c466c80-6dce-11eb-8ac4-fc69fb626f55.png">

Loaded up all those mods and no crash, this is perplexing.

**Comment by JLewis1309** [comment]
it doesnt seem like its the mods themselves, i think its something to do with the number of mods, updating fabric API made it slightly worse where now i have to have 1 extra mod uninstalled but doesnt seem to matter which one i disable

**Comment by JLewis1309** [comment]
like i can just randomly disable any mod and it seems to load

**Comment by kwpugh** [comment]
can you post a full launcher log please?

**Comment by JLewis1309** [comment]
https://pastebin.com/j1GsPTw6 u mean this?

**Comment by kwpugh** [comment]
yeah

**Comment by JLewis1309** [comment]
i just joined your Discord Server if you'd rather DM on there instead of further clogging up this issues thread lol

**Comment by kwpugh** [comment]
Unable to. re-produce.
