### ISSUE TITLE
Fail to compile mod

### ISSUE THREAD

**Issue by CrisInuyasha** [kwpugh/gobber_fabric#21]
I tried compiling the mod but it seens a dependency is not accessible:

Could not GET 'https://dl.bintray.com/kyrptonaught/customportalapi/com/kwpugh/pugh_lib_fabric_1.17/1.1.3/pugh_lib_fabric_1.17-1.1.3.pom'. Received status code 403 from server: Forbidden

**Comment by kwpugh** [comment]
Sorry, Pughlib is not publicly available.   Why the custom portals is tacked on to the front of that is odd.
