### ISSUE TITLE
[1.19.2] Add trinkets support to the separate ring mods

### ISSUE THREAD

**Issue by vizthex123** [kwpugh/gobber_fabric#23]
[Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets) seems to have replaced Curios in 1.19.2, and it'd be nice if support for it was in both this and each ring's mod.

**Comment by kwpugh** [comment]
I have no plans for Trinkets support.

**Comment by vizthex123** [comment]
any reason why?

**Comment by kwpugh** [comment]
I had curios in the past.  I do not like Trinkets

**Comment by vizthex123** [comment]
any reason why?
