### ISSUE TITLE
[1.16.5] Ores and blocks doesn't drop anything.

### ISSUE THREAD

**Issue by panbanann** [kwpugh/gobber_fabric#24]
Newest .jar for 1.16.5: Gobber2-Fabric_1.16.5-2.3.76
None of the gobber blocks can be mined with any tools or any way.
I was checking your block registration and I may be newby in terms of modding but It doesn't seem like `FabricMaterialBuilder` contain anything that can match `(MaterialColor.STONE)`.
Correct me if I'm wrong. I have no idea how you manage to make it work. 
Your 1.17 register looks more like the one that should work:
`(FabricBlockSettings.of(Material.STONE)`
Any chance you could still fix it for this version?
Regards

**Comment by kwpugh** [comment]
Hmm.  I just tested breaking the blocks, glass, and ores with diamond and netherite, and they break fine and drop blocks.  You might have another mod that is messing things up.

Are there any mods that that you have disabled an ore/material that includes pickaxe?   Some authors forgot to make their addition to FabricToolTag JSON optional?

Please attach a recent latest.log so I can see what else you are running.

**Comment by panbanann** [comment]
Sorry for making those statements. Yeah, it was the fault of another mod. The better nether config was messing it up then you disable either cincinaste (or however it's spelt) or ruby pickaxes. I will write the ticket on their Github. Thanks for helping and sorry for blaming you.
