### ISSUE TITLE
[1.17] - Server Console Messages

### ISSUE THREAD

**Issue by xanthian** [kwpugh/gobber_fabric#26]
[main/WARN]: Reference map 'rhino-fabric-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message

[main/WARN]: Reference map 'RingOfAttraction-Fabric-1.17.1-refmap.json' for ring_of_attraction.mixins.json could not be read. If this is a development environment you can ignore this message

---

Looks like this is declared in the ring_of_attraction.mixins.json but doesnt exist

  },
  "refmap": "RingOfAttraction-Fabric-1.17.1-refmap.json"
}

**Comment by kwpugh** [comment]
I  will address in 1.18.1, I'm not updating 1.17 anymore.
