### ISSUE TITLE
excessive log messages

### ISSUE THREAD

**Issue by artfish** [kwpugh/gobber_fabric#3]
This is not necessarily a bug, but the mod outputs an excessive amount of log messages, especially one for every broken block it seems, for instance like "[06:58:17] [Server thread/INFO]: [STDOUT]: mining level: 3". I do understand the importance of logging for debugging reasons and the beta status of the project, but maybe it could be turned down a notch in this case? I became aware of this behavior when MultiMC complained about the logs more than 10k lines and disabled the console.

edit: I just read through the source, the log output is in "gobber_fabric/src/main/java/com/kwpugh/gobber2/items/tools/endtools/PaxelEndStars.java" line 91

**Comment by kwpugh** [comment]
Thanks for pointing that out, I forgot that one.  It will be removed next release.
