### ISSUE TITLE
Farmers ring vulnerablity 

### ISSUE THREAD

**Issue by genericbrain** [kwpugh/gobber_fabric#31]
id like to make a request after an issue i had.

the new glow lichen thing from the caves has an expansive grow mechanic, // i takes over the world if even a bit is within range my save file is ruined 

i'd like to request if possible a black list option for the plants if you are so kind make it default to not grow "glow lichen" 

i dont know if this plants behavior is present in any other but seems important to look into

for you time and attention thanks

**Comment by kwpugh** [comment]
I will be looking into this when I return to modding in mid May

**Comment by kwpugh** [comment]
Handled with #16
