### ISSUE TITLE
All Gobber ores are mineable with wooden pickaxe

### ISSUE THREAD

**Issue by Nekobrenna** [kwpugh/gobber_fabric#39]
I don't know why this is happening, but I put Gobber onto our server (version 1.19.2-2.6.61) and it is mineable with a WOODEN pickaxe. Not even a modded wooden hammer pickaxe. It is a vanilla wooden pickaxe and it can mine gobber, nether gobber, AND end gobber. One of my server members reported the broken mod and I tried to fix it in the config.... but there is no option to fix how to mine it.

Please help.

**Comment by Vicente015** [comment]
I have the same issue (version 1.19.2-2.6.61)

![imagen](https://github.com/kwpugh/gobber_fabric/assets/33096355/de17237d-489f-498e-9eb5-451b6c3caddd)

**Comment by nullx404x** [comment]
whats your modlist? I have the same problem but when I open the mod alone I have no issues. Some mod is conflicting with it.

**Comment by Nekobrenna** [comment]
This is the modlist straight from my pack download:

[Vanilla Hammers (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers)
[Mermod [FABRIC] (by ThatPreston)](https://www.curseforge.com/minecraft/mc-mods/mermod-fabric)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Ultris: Boss Expansion (by limesplatus)](https://www.curseforge.com/minecraft/mc-mods/ultris-boss-expansion)
[When Dungeons Arise - Fabric! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Display Case (by ChappiePie)](https://www.curseforge.com/minecraft/mc-mods/displaycase)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[More Axolotl Variants API (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavapi)
[More Frogs - Fabric/Quilt/Forge (by frikinjay)](https://www.curseforge.com/minecraft/mc-mods/more-frogs-fabric)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Magnum Torch (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[Carpet-Fixes (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/carpet-fixes)
[XP Obelisk (by Meridanus)](https://www.curseforge.com/minecraft/mc-mods/xp-obelisk)
[Quark Crystals [EMBEDDED IN TERRAINS] (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/quark-crystals)
[Polymorph (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Adorn (by Juicebus)](https://www.curseforge.com/minecraft/mc-mods/adorn)
[Vertical Slabs Compat (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat)
[More Banner Features (by KxmischesDomi)](https://www.curseforge.com/minecraft/mc-mods/more-banner-features)
[Recipe Book Delight (by melontini)](https://www.curseforge.com/minecraft/mc-mods/recipe-book-delight)
[Expanded Delight [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Carpet (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet)
[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)
[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)
[Create Decoration Casing (by TheLynkYT)](https://www.curseforge.com/minecraft/mc-mods/create-decoration-casing)
[Plushie Mod (by Link_911)](https://www.curseforge.com/minecraft/mc-mods/plushie-mod)
[Additional Structures (Fabric/Quilt) (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures-fabric)
[Mod Menu (by Prospector)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[The Graveyard (FABRIC) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric)
[Echo Chest [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/echo-chest)
[Better Villages - Fabric (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-fabric)
[Villagers Respawn (Now with FORGE and FABRIC versions) (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/villagers-respawn)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[A Man With Plushies (AMWPlushies) (by maxsteelbro)](https://www.curseforge.com/minecraft/mc-mods/a-man-with-plushies)
[Ender Dragon Drops Head (Fabric) (by 5H1NY_M3W)](https://www.curseforge.com/minecraft/mc-mods/ender-dragon-drops-head-fabric)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[MidnightControlsExtra (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/midnightcontrols-extra)
[Just Player Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
[Effective Crystals (by trique06)](https://www.curseforge.com/minecraft/mc-mods/effective-crystals)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Conjuring (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/conjuring)
[Handcrafted (by kekie6)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Configuration [Fabric | Forge] (by Toma1O6)](https://www.curseforge.com/minecraft/mc-mods/configuration)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Awesome Dungeon Ocean edition - Fabric (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-edition-ocean-fabric)
[Magick: Potions and Pearls (by magick_arcanist)](https://www.curseforge.com/minecraft/mc-mods/magick-potions-and-pearls)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Pig Pen Cipher (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Fabric Waystones (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
[Fabric Craftable Enchanted Golden Apple (by SmushyTaco)](https://www.curseforge.com/minecraft/mc-mods/fabric-craftable-enchanted-golden-apple)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Library Ferret - Fabric (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-fabric)
[Mob Scarecrows (by ArcanePigeon)](https://www.curseforge.com/minecraft/mc-mods/mob-scarecrows)
[Nether Chested [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/new-nether-chest)
[Better Spawner Control (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/better-spawner-control)
[Smarter Farmers (farmers replant) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant)
[Nether Coords (Fabric) (by CaelenO42)](https://www.curseforge.com/minecraft/mc-mods/nether-coords-fabric)
[Mythic Mounts (by chirpycricket__)](https://www.curseforge.com/minecraft/mc-mods/mythic-mounts)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[Cardinal Components (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
[Dark Utilities (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
[Coffee Delight (by someoneice)](https://www.curseforge.com/minecraft/mc-mods/coffee-delight)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Fishing Aquatica (by Twitching_Pixel)](https://www.curseforge.com/minecraft/mc-mods/fishing-aquatica)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[Head Name Fix (by manyrandomthings)](https://www.curseforge.com/minecraft/mc-mods/head-name-fix)
[Simple Hats (by fonnymunkey)](https://www.curseforge.com/minecraft/mc-mods/simplehats)
[Gobber [FABRIC] (by kwpugh)](https://www.curseforge.com/minecraft/mc-mods/gobber-fabric)
[Villager Hats Mod (by PinkGoosik)](https://www.curseforge.com/minecraft/mc-mods/villager-hats-mod)
[Universal Bone Meal [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/universal-bone-meal-forge)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Polymer (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/polymer)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Stoneworks [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/stoneworks)
[Configured (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured-fabric)
[Bamboo Everything (Forge/Fabric) (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/bamboo-everything)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Iceberg [Fabric] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[More Geodes (by TheDeathlyCow)](https://www.curseforge.com/minecraft/mc-mods/emerald-geodes)
[Eden Ring (by paulevs)](https://www.curseforge.com/minecraft/mc-mods/eden-ring)
[Enchant the Rainbow (by Pepperoni__Jabroni__)](https://www.curseforge.com/minecraft/mc-mods/enchant-the-rainbow)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[AdventureZ (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/adventurez)
[Customizable Elytra (Fabric) (by Hidoni)](https://www.curseforge.com/minecraft/mc-mods/customizable-elytra-fabric)
[Chimes (by BlewberryPie)](https://www.curseforge.com/minecraft/mc-mods/chimes)
[Miniblock Merchants (by chimericdream)](https://www.curseforge.com/minecraft/mc-mods/miniblock-merchants)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Arcane Lanterns [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/arcane-lanterns)
[Jade Addons (Fabric) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons-fabric)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Culinary Construct (Forge/Fabric/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/culinary-construct)
[Cultural Delights [Fabric] (by MrSterner_)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights-fabric)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Charm (by svenhjol)](https://www.curseforge.com/minecraft/mc-mods/charm)
[XP Obelisk Additions (by Meridanus)](https://www.curseforge.com/minecraft/mc-mods/xp-obelisk-additions)
[Plasmo Voice (by KPidS)](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice)
[Droplight (by BanzettaDev)](https://www.curseforge.com/minecraft/mc-mods/droplight)
[Elytra Slot (Fabric 1.16.1 - 1.19.2) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot-fabric)
[The Missing Villages (by bigreefer420)](https://www.curseforge.com/minecraft/mc-mods/the-missing-villages)
[Forge Config API Port [Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Ender Dragon Egg Respawn (Fabric) (by Intezium)](https://www.curseforge.com/minecraft/mc-mods/ender-dragon-egg-respawn-fabric)
[The Bumblezone (Quilt/Fabric) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric)
[Straw Statues (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/straw-statues)
[Dungeon Now Loading (by hexnowloading)](https://www.curseforge.com/minecraft/mc-mods/dungeon-now-loading)
[Chef's Delight [Fabric] (by redstone3game)](https://www.curseforge.com/minecraft/mc-mods/chefs-delight-fabric)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[MVS - Moog's Voyager Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures)
[Create Ore Excavation (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/create-ore-excavation)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Leaves Be Gone (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone)
[Collector's Album [Fabric | Forge] (by Toma1O6)](https://www.curseforge.com/minecraft/mc-mods/collectors-album)
[Nether Depths Upgrade (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[CTM Refabricated (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/ctm-refabricated)
[Bartering Station [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/bartering-station)
[Goodall (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/goodall)
[Farmer's Respite (Fabric) (by JustoPlayzz_)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite-fabric)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Universal Graves (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/universal-graves)
[XP Storage (by sfinc)](https://www.curseforge.com/minecraft/mc-mods/xp-storage)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Quartz Elevator (by atonkish)](https://www.curseforge.com/minecraft/mc-mods/quartz-elevator)
[Probably Chests (by ArcanePigeon)](https://www.curseforge.com/minecraft/mc-mods/probably-chests)
[Ender Tap (for Fabric & Carpet) (by sjoopies)](https://www.curseforge.com/minecraft/mc-mods/ender-tap-for-fabric-carpet)
[MidnightControls (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/midnightcontrols)
[Trading Post [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/trading-post)
[XP Storage - Trinkets (by sfinc)](https://www.curseforge.com/minecraft/mc-mods/xp-storage-trinkets)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Way Much Faster Oxidize (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/way-much-faster-oxidize)
[Roberts Collection (by RobertoImI)](https://www.curseforge.com/minecraft/mc-mods/roberts-collection)
[Repurposed Structures (Quilt/Fabric) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[VillagersPlus (FABRIC) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/villagersplus-fabric)
[Shoppy (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/shoppy)
[Zombify Villager (by Fampat)](https://www.curseforge.com/minecraft/mc-mods/zombify-villager)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Oh The Biomes You'll Go Refabricated (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric)
[More Music Discs [Fabric/Forge] (by 1_block_microwave)](https://www.curseforge.com/minecraft/mc-mods/more-mc-music-discs)
[Just Mob Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)
[Prism [Fabric] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/prism-fabric)
[Goblin Traders [Fabric] (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblintraders-fabric)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[More Axolotl Variants Mod (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavm)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Hearty Trinkets (by traverse_joe)](https://www.curseforge.com/minecraft/mc-mods/hearty-trinkets)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[SpoornPacks (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/spoornpacks)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
[myLoot (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/myloot)
[Simple Copper Pipes (by AViewFromTheTop)](https://www.curseforge.com/minecraft/mc-mods/simple-copper-pipes)
[Adaptive Tooltips (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/adaptive-tooltips)
[Cull Clouds (by yugamiineena)](https://www.curseforge.com/minecraft/mc-mods/cullclouds)
[Carpet Extra (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet-extra)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[Traveler's Backpack [Fabric] (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric)
[Paradise Lost (by ImmortalDevs)](https://www.curseforge.com/minecraft/mc-mods/paradise-lost)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Sky Villages [Fabric] (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/sky-villages-fabric)

**Comment by kwpugh** [comment]
I have yet to figure this out.  Interestingly, updating the mod to 1.20 I had to rewrite the code due to some breaking change by mojang and it no longer is a problem.
