### ISSUE TITLE
Gobber causes a NullPointerException upon using hammer on gobber ore

### ISSUE THREAD

**Issue by noclueumbreon** [kwpugh/gobber_fabric#4]
Log in pastebin: https://pastebin.com/jXK2LyMm

Title. Apparently connected to mining speed modifications, somehow? Will test further with currently enabled mods.

**Comment by kwpugh** [comment]
What did you do before the crash?   Seems like you were using the hammer.  On what?

**Comment by kwpugh** [comment]
directly or indirectly, I mean, on the Gobber ore?

**Comment by kwpugh** [comment]
I think I see where the problem is.

**Comment by noclueumbreon** [comment]
Directly on the gobber ore causes the crash. Mining an adjacent block allows the non ore blocks around to be mined in a typical manner, but the block directly mined is not broken.

Example: X is Gobber Ore, O is stone;
X**OO**
XO**O**
**O**X**O**
Mining the middle block will break the bolded blocks.

The hammer was obtained via REI's cheat mode, and tested with a manually crafted one. It's also tested with an enchanted one- a member of a server I admin reported the issue, and I tested it myself on the server and in a private world.
Sorry for the delay! I was asleep. Let me know anything else that may help.

**Comment by kwpugh** [comment]
I cannot replicate the error.  I suspect it is a conflict with another mod that is doing a Mixin into pickaxe class.

Please try this version on your setup and let me know if it still crashes.

[Gobber2-Fabric_1.16.5-2.3.69.jar.zip](https://github.com/kwpugh/gobber_fabric/files/6025669/Gobber2-Fabric_1.16.5-2.3.69.jar.zip)

**Comment by noclueumbreon** [comment]
It's likely a mod conflict error, yeah. I'll test the version you sent- there should be a list of mods in the crash report, so at least it should be possible to figure out what's screwing it up and mark the two as non-compatible?
It's possible to mine the ore with regular pickaxes as well as with Gobber tools, but it seems like whatever calculates the block's breaking time is being broken- even in creative, the blocks refused to break.

**Comment by noclueumbreon** [comment]
I can also provide the modpack we're using, if that may help? It appears to happen on Nether Gobber ore as well, but I haven't tested it on End. The error does not occur on the other modded ores, as far as I know- but I'll test it.

**Comment by kwpugh** [comment]
That would make sense if another mod is playing with the same pickaxe code.  Since the hammer is not a vanilla tool class, it is made from the generic mining tool class and then I get it's mining speed from either the diamond or netherite pickaxe.

**Comment by noclueumbreon** [comment]
Using the version of the mod you provided fixed the issue. It's probably something to do with RPGstats, or some other mod which edits the player's mining speed. I'll test it on the server and update if any more crashes occur- is it ok if I ask what you changed? I look at minecraft code as a hobby, and this is really interesting!
Thanks for the help and the politeness.

**Comment by kwpugh** [comment]
I changed the method I override for mining speed to return the default stack:

`	@Override
	public boolean isEffectiveOn(BlockState state)
	{
		System.out.println("stack: " + getDefaultStack());

		if (Items.DIAMOND_PICKAXE.isEffectiveOn(state))
		{
			return true;
		}

		return Items.DIAMOND_PICKAXE.getMiningSpeedMultiplier(getDefaultStack(), state) > 1.0f;
	}`

**Comment by noclueumbreon** [comment]
I think I understand how that code works. Would it be outside the scope of this bug report to ask why there needs to be a mining speed override, and what returning it to default would change?

**Comment by noclueumbreon** [comment]
I'm also unsure whether this should be marked as closed or not, as the changes seem like a workaround- please excuse me if I am wrong, I don't really have professional experience reading code.

**Comment by kwpugh** [comment]
It does fix it, I was returning null previously and another mod picked it up and caused the null pointer exception.  The only thing I don't know (or really care) is which mod was picking up the null value.   As long as they don't pick up null value, all is well.

**Comment by noclueumbreon** [comment]
Alright, thank you! I'll close the issue, but I have one last question- is this version going to be released on curseforge, or should I keep it downloaded and put it in the modpack?

**Comment by kwpugh** [comment]
I will be pushing to curseforge shortly

**Comment by noclueumbreon** [comment]
Thank you for helping! I'll close the issue now- have a good day!
