### ISSUE TITLE
[1.18.2] Medallion of Water Breathing does nothing

### ISSUE THREAD

**Issue by The-OmegaMale** [kwpugh/gobber_fabric#4]
I'm playing on a fairly large 1.18.2 modpack including origins so that might be the problem. I picked the merman origin and I crafted the medallion so I could breathe on land but I still suffocate. I don't know why this doesn't work while water breathing potions and other charms do.

**Comment by kwpugh** [comment]
what mod adds the merman origin?

the medallion works differently from the  water breathing potions.  Those restore the player's supply  of air.  The medallion cancels damage to  the player due to  drowning.  It might not be compatible with origins.  If  I can find the source code to the merman, I can see.

**Comment by kwpugh** [comment]
the medallion is intended for use by normal players underwater.  It prevents damage from drowning. I'm guessing the merman takes suffocation damage when on land.

**Comment by The-OmegaMale** [comment]
The merman is from the original origins mod

https://www.curseforge.com/minecraft/mc-mods/origins

**Comment by kwpugh** [comment]
looking at their  source  code, the origin power  specifically  checks  for the vanilla water breathing or conduit power, which I do  not use.  
<img width="1351" alt="Screen Shot 2022-07-27 at 7 15 29 AM" src="https://user-images.githubusercontent.com/8809210/181244504-7e9b60b6-40ab-44cc-b936-7ef59dc3fe73.png">

The Medallion of the Sea use the vanilla Conduit Power, which might work for you.

**Comment by kwpugh** [comment]
Nvm, that won't work since the medallion  of the sea doesn't activate unless you are submerged in water.

you will  need to look at other  mods for options.

**Comment by The-OmegaMale** [comment]
Can't you just make it so it activates all the time?

**Comment by kwpugh** [comment]
no, it makes  no sense to have it on all the time for normal players.

**Comment by kwpugh** [comment]
though I  could add a config option for that inn the future.

**Comment by The-OmegaMale** [comment]
No It doesn't work

**Comment by kwpugh** [comment]
oh well, it was worth a shot.   You will have to find a mod that is designed for compatibility with Orgins.
