### ISSUE TITLE
1.19.2 Issue with Advanced netherite mod

### ISSUE THREAD

**Issue by AaronTheLeopard** [kwpugh/gobber_fabric#43]
Pickaxes from Advanced netherite mod can mine nether lucky gobber ore but not common nether gobber ore, why ?

**Comment by kwpugh** [comment]
Lucky blocks only need iron level mining or higher.  Nether Gobber requires a Gobber pickaxe level.  By design.

**Comment by kwpugh** [comment]
More specifically, the advanced nephrite tools use mining 4 (netherite) and nethergobber ore requires mining level 5 (Gobber level).
