### ISSUE TITLE
Broken images on Gobber2 Curseforge mod page

### ISSUE THREAD

**Issue by kingstairs** [kwpugh/gobber_fabric#49]
Almost none of the images are currently displaying on the page:

Example:
https://media.forgecdn.net/attachments/480/327/screen-shot-2022-07-23-at-9.png

Error (if you open image in another tab/window):
NoSuchKeyThe specified key does not exist.attachments/480/327/screen-shot-2022-07-23-at-9.png58EWJDTJWX1DZPD48Urtqo1Ba3FXraUutMLCGZ5+BRP0aTQ9B88gB6Gp0GbcszW1R5+iBLfXmtzDerz+Ly7HVSWuxXM=

**Comment by kwpugh** [comment]
may be a network distribution, I'm seeing them.   I will check again later.

**Comment by kwpugh** [comment]
I'm seeing the images just fine, not sure what might be happening.
