### ISSUE TITLE
Feature request: Trinkets compatibility

### ISSUE THREAD

**Issue by calloatti** [kwpugh/gobber_fabric#5]
Could you make the 1.18.2 and later versions compatible with Trinkets please? Curios is deprecated. Thanks

https://www.curseforge.com/minecraft/mc-mods/trinkets

**Comment by calloatti** [comment]
This mod: https://www.curseforge.com/minecraft/mc-mods/ring-of-attraction-fabric

**Comment by kwpugh** [comment]
not planning to support trinkets.
