### ISSUE TITLE
[1.16.5] End Gobber Ore Generation

### ISSUE THREAD

**Issue by coreytr** [kwpugh/gobber_fabric#5]
End Gobber Ore does not generate anywhere in the end, tested on multiple new worlds (removed BYG to test as well)

**Comment by kwpugh** [comment]
Which version of Gobber?

**Comment by coreytr** [comment]
Latest version (March 19) - and I began Gobber on the recent but former release, experiencing the same issue there

**Comment by kwpugh** [comment]
Likely a conflict with another mod.  I'm playing with the latest v71 and ores a plenty in the end

**Comment by coreytr** [comment]
Alright. If you dont close this, I'll add in which mod it conflicts with once I deduce

**Comment by kwpugh** [comment]
ok, thanks.

**Comment by kwpugh** [comment]
I would check mods that either 1) add ores to the game or 2) add biomes or add things to biomes (i.e. trees, plants, etc.).  In 1.16.5 ore generation is handled through biomes and another mod might be stepping on mine.

**Comment by coreytr** [comment]
Ok. I have only a few mods for the end including BYG, Better End, and Tech Reborn which also spawns ores in the End.

**Comment by kwpugh** [comment]
Did you try without Better End?  I have a feeling.

**Comment by kwpugh** [comment]
Not confirmed yet.  Cannot replicate on my test environment or production server I play on.

**Comment by coreytr** [comment]
Yes, not confirmed. I've been testing extensively; this is mainly an incompatibility issue. I've gotten the list of potential culprits down to about 5 or 6 mods, still testing and getting closer

**Comment by coreytr** [comment]
Bingo! The mod titled, "Into the Omega", is causing this issue. This mod also adds an ore to the end, and when the two mods are run in tandem neither ores from either mod generate in the End

**Comment by kwpugh** [comment]
You have a link on that mod?  I don't see a mod called "into the Omega" on Curseforge.

**Comment by coreytr** [comment]
https://www.curseforge.com/minecraft/mc-mods/into-the-w

**Comment by kwpugh** [comment]
yeah found it.  It re-writes the end in the ore feature.  Not sure I can do anything about that.

**Comment by coreytr** [comment]
Quick work, you are impressive. Im going to opt to remove it, it seems problematic from the stem and it hasn't been updated for a while. Removing that mod has also ceased the occasional crashes now too. 

Thanks for being so timely and sharp. I appreciate the creativity and ideas you add to Minecraft with your mod. Cheers
