### ISSUE TITLE
Ring of the Miner bugged in the nether

### ISSUE THREAD

**Issue by Stoob7** [kwpugh/gobber_fabric#6]
Using ring of the miner to mine the nether for ancient debris.
Was initially working correctly, but after a server crash now the ring only mines the same 20% of the blocks in the selected area while in the nether.
Still works fine in the overworld.
Multiple uses of the ring in the same area in the nether does not mine additional blocks.

![image_2022-08-25_005734124](https://user-images.githubusercontent.com/112037086/186544365-e82db260-9af2-47dc-956f-d638010ec830.png)

**Comment by kwpugh** [comment]
Which version of the mod are you using

**Comment by kwpugh** [comment]
And I think this might be an issue with multiple users using the ring at same time.  

you might want to try the "ringMinerCentralizedBreaking" feature in config, which is designed for servers.

![Screen Shot 2022-08-24 at 7 14 48 PM](https://user-images.githubusercontent.com/8809210/186546014-0f70e8b9-4d45-4dad-89f3-84718a476610.png)

**Comment by Stoob7** [comment]
Hi thanks for getting in touch! Sorry for the late reply, I don't play
super frequently right now, I'll be trying the suggestion out today in a
minute, I'll let you know how it goes!

the version of the mod is : 2.6.26

Kind regards,
Matt

**Comment by Stoob7** [comment]
That solution works perfectly, thanks again!
