### ISSUE TITLE
[1.16.5] pig crashes server

### ISSUE THREAD

**Issue by Monster-Zer0** [kwpugh/gobber_fabric#7]
when a pig attempts to go through portal we get this server crash

https://paste.alloffabric.com/iguqowimog.yaml

**Comment by kwpugh** [comment]
Which Dim?

Can players go through the portal without issue?

Do you have a mod that changes/updates vanilla pigs?

**Comment by Monster-Zer0** [comment]
Caving dim.

players can, yes. so can a pig most of the time

charm is the mod that varies pig textures https://www.curseforge.com/minecraft/mc-mods/charm

**Comment by kwpugh** [comment]
Has this happened any further using the latest version of Gobber on 1.16.5?   It has a new version of the CustomPortalsAPI?

**Comment by kwpugh** [comment]
No further reports, closing.
