### ISSUE TITLE
[1.18.2] Powah blocks don't break with hammer

### ISSUE THREAD

**Issue by Seceroth** [kwpugh/gobber_fabric#7]
Hello,
I've added the #gobber2:hammer_additions tag to a few blocks from other mods expecting it to result in the hammers from this mod to break the blocks in 3x3/5x5, however it does not work as expected. The blocks are not mined with the hammer's 3x3/5x5.

Versions:
Fabric Loader 0.14.9
Fabric API 0.58.0+1.18.2
Gobber2 2.5.80

**Comment by kwpugh** [comment]
I'll take a look.  what blocks did you add?

**Comment by kwpugh** [comment]
I remember, that tag is defunct.  I will remove from future release too avoid confusion.

**Comment by kwpugh** [comment]
All properly tagged mod blocks that are within the hammer's mining level should be broken, so really no need to have a tag.

**Comment by Seceroth** [comment]
This is the hammer_additions.json file:
```
{
  "replace": false,
  "values": [
	"powah:dry_ice",
	"powah:uraninite_ore",
	"powah:uraninite_ore_poor",
	"powah:uraninite_ore_dense",
	"powah:deepslate_uraninite_ore_dense",
	"powah:deepslate_uraninite_ore",
	"powah:deepslate_uraninite_ore_poor",
	"valley:mixed_ore",
	"valley:deepslate_mixed_ore"
  ]
}
```

Alright, so, anyway to make it work differently?

**Comment by kwpugh** [comment]
looking at their source code, it should work.  just needs to be iron mining level.  which hammer are you using?

**Comment by Seceroth** [comment]
![Knipsel](https://user-images.githubusercontent.com/20866237/190466195-5d70ff4a-3f4c-4a50-8f33-31489cdaa96c.PNG)
Tested all of the Gobber hammers.

**Comment by kwpugh** [comment]
Yeah, I have no idea why it doesn't break the surrounding blocks, their source code looks correct.

**Comment by kwpugh** [comment]
What mod is the valley:mixed_ores from?

**Comment by kwpugh** [comment]
Ok, I found the issue.  It turns out that Powah  adds a BlockEntity to the ores (very very uncommon thing to do.)

I intentional exclude breaking surrounding blocks that contain block entities because it canna screw up machines, which are the blocks that usually have block entities.

at this point, not sure if this is something I am going to try to fix.  An ore with a block entity seems like a really edge case.

<img width="1166" alt="Screen Shot 2022-09-17 at 7 43 47 AM" src="https://user-images.githubusercontent.com/8809210/190857457-3c33a7b7-cfd3-4e20-9e71-0a31f11662d0.png">

**Comment by Seceroth** [comment]
Valley:mixed_ores is from ValleyCraft.

I see, thanks for looking into it.
Maybe re-enabling the hammer_additions file would work? 😄

**Comment by kwpugh** [comment]
I chatted with the Powah author:

<img width="589" alt="Screen Shot 2022-09-17 at 8 32 51 AM" src="https://user-images.githubusercontent.com/8809210/190859689-b3624a8c-423b-4be5-9e39-00a6072e49c4.png">

Should be fixed on their end at some point.

**Comment by kwpugh** [comment]
what version of valley craft are you using, I do not see any ores in their source code

**Comment by kwpugh** [comment]
Powah is implementing a class (AbstractBlock) that contains a block entity, even though a block entity is not created for the ores.  The existence of the block entity is why the ores do not pass my block breaking logic.

**Comment by Seceroth** [comment]
valley-craft-2.3.1-1.18.2

**Comment by kwpugh** [comment]
the valley craft author only has v1.0 on GitHub, so I cannot see what they are doing.  It might be the same BE issue as Powah.

**Comment by kwpugh** [comment]
I'm guessing no fixes coming from Valley Craft, discontinued.

<img width="909" alt="Screen Shot 2022-09-17 at 8 47 00 AM" src="https://user-images.githubusercontent.com/8809210/190860247-1096c511-961a-491f-873b-679215928f41.png">

**Comment by Seceroth** [comment]
Yea, their GitHub and Twitter is active, but no idea what their plans are. Apparently ValleyCraft: Wilder Horizons?

Anyway, I assume the hammer_additions tag is not coming back?

**Comment by kwpugh** [comment]
no, it was not really a good idea from the start.

**Comment by Seceroth** [comment]
That would just desync right? Since whatever data the server has is leading?
Might I suggest a config then to add blocks to?

**Comment by kwpugh** [comment]
no desync, the client side datapack would trump.

config is similar problem, Cloth Config does not have an explicit server-only method.

**Comment by Seceroth** [comment]
> no desync, the client side datapack would trump.

... That makes no sense.

It's not that big a deal I suppose, but maybe an idea to add it at some point if possible. :)

**Comment by kwpugh** [comment]
status: awaiting update in Powah to switch ores from implementing AbstractBlock.

**Comment by kwpugh** [comment]
I'm no longer tracking this.
