### ISSUE TITLE
[1.16.5] Ring of Vision does not provide it's effect.

### ISSUE THREAD

**Issue by AlexisBloodwood** [kwpugh/gobber_fabric#8]
Basically what it says on the tin, I'm wanting to use it while in the Caving Dimension instead of carrying around the Staff of the Stars however I encountered the following issue. :(

[Video containing the issue.](https://youtu.be/twaLcipGmT8)

**Comment by kwpugh** [comment]
What are the versions of fabric and Gobber?

I just tried Gobber2-Fabric_1.16.5-2.3.71 and the Ring of Vision worked just fine.

**Comment by AlexisBloodwood** [comment]
Gobber2 1.16.5 2.3.71 with API 0.31.5 and Loader 0.11.3

**Comment by kwpugh** [comment]
post a system log from when you tried using the ring, maybe I can find something there.   Since it works on my end and for everyone else using it, I'm guessing it is a specific conflict with another mod you have installed.

**Comment by AlexisBloodwood** [comment]
[Minecraft Ring of Vision Log](https://github.com/kwpugh/gobber_fabric/files/6258981/Minecraft.Ring.of.Vision.Log)

Neither 0bin nor Github likes my log since its so long :/

**Comment by kwpugh** [comment]
As I suspected, no specific error message is generated.  Since I cannot replicate the issue, not much I can do about it.   I expect that is a conflict with another mod.  That ring is about as simple an item as one can get with a stock right-click and a timed vanilla Night Vision effect.   I wouldn't know where to begin to chase down a mod conflict like this.

**Comment by kwpugh** [comment]
I tried Optifine/Optifabric and that works fine.

I noticed you have some other trinkets in slots, did you try removing them to see if it works?

**Comment by AlexisBloodwood** [comment]
Every trinket and curio, including armor was taken off and put in a chest yet no dice. Maybe its something to do with the caving dimension?

**Comment by kwpugh** [comment]
Can you try a night vision potion?   I doubt the caving dimension is the issue, I believe something is blocking your night vision "visual" client side.

**Comment by AlexisBloodwood** [comment]
Potions and the /effect command work, just used the command when going out exploring at night

**Comment by kwpugh** [comment]
Still cannot replicate this issue.  Ring of Vision appears to be working fine.

**Comment by AlexisBloodwood** [comment]
Hey, it's alright man. Don't stress yourself over this; its been four months! Plus we have 1.17/18 to look forward too. I really appreciate you looking into the issue for me, I'll find a work-around somehow.
