### ISSUE TITLE
[Suggestion] Would it be possible to make Ring of Attraction work with Trinkets for Fabric 1.18+?

### ISSUE THREAD

**Issue by StunnerPony** [kwpugh/gobber_fabric#8]
Since [Curios API](https://www.curseforge.com/minecraft/mc-mods/curios-fabric) has been discontinued for Fabric since 1.17, and the mod doesn't work with [Trinkets API](https://www.curseforge.com/minecraft/mc-mods/trinkets) at the moment.

Just a suggestion. Really love the mod tho <3

**Comment by kwpugh** [comment]
I do not want to use Trinkets in my mods.   If you are short on space in inventory, gobber 1.19.2 has the ability to run many of the rings/medallions from within the player's enderchest.  There is a config option to enable it.

The following will work in the enderchest:

Medallions:
- Breathing
- Experience
- Lesser, normal, and Greater Healing
- Hero
- Sea
- Shielding
- Suffering

Rings:
- Attraction
- Curing
- Haste
- Luck
- Phoenix
- Repair
- Strength
- Swiftness
- Vision

**Comment by kwpugh** [comment]
When you enable the config option, those items that work in enderchest will have an additional tooltip message indicating as such.

**Comment by StunnerPony** [comment]
Understandable. Still, thanks for the reply :)
