### ISSUE TITLE
[1.18.2] No QuickUse enchantment on table

### ISSUE THREAD

**Issue by dbock1989** [kwpugh/gobber_fabric#9]
As the title says, QuickUse enchantment is unobtainable on the enchantment table. Is there a special way to get it or is this a bug? 

MC Version 1.18.2 Fabric

**Comment by kwpugh** [comment]
Are you playing a modpack?  Might check if it is disabled in the config.  It should be available in the enchant table, as chest treasure and in villager trades.

**Comment by dbock1989** [comment]
I'll take a look at the configuration again. I never saw an option to
enable/disable. I actually added the Gobber2 mod without altering it to
AOF5 modpack. I'll update in just a little while.

I appreciate your help!

**Comment by kwpugh** [comment]
I just noticed you wrote that you are using 1.18.2.   In 1.18.2, you can only get QuickUse from a village Librarian.

There is no config options in that version.

**Comment by dbock1989** [comment]
Oh! Fantastic. I knew I had to be doing something wrong. I really appreciate it!! Keep up the great work. I love your mods!

**Comment by kwpugh** [comment]
Good luck, and enjoy!
